DROP TABLE IF EXISTS expenses CASCADE;
DROP TABLE IF EXISTS accounts CASCADE;

CREATE TABLE accounts (
	id SERIAL PRIMARY KEY,
	first_name VARCHAR(100) NOT NULL,
	last_name VARCHAR(100) NOT NULL,
	email VARCHAR(100) UNIQUE NOT NULL,
	password VARCHAR(100) NOT NULL,
	expense_limit NUMERIC(6, 2) DEFAULT 0 NOT NULL
);


CREATE TABLE expenses (
	id SERIAL PRIMARY KEY,
	account_id INTEGER NOT NULL REFERENCES accounts(id),
	amount NUMERIC(7, 2) NOT NULL,
	description VARCHAR(200),
	category VARCHAR(100) NOT NULL,
	added_at DATE NOT NULL
);


